### ISSUE TITLE
Safari Compatibility

### ISSUE THREAD

**Issue by saifcharaniya** [sfu-db/reprowd#2]
I've noticed that on Safari (v9.1.1), while using ImageCmp as the presenter mode, the images on the pybossa server do not load on testing or on a published project.  They do however load using FireFox on the same computer.  Using ImageLabel this is not am issue.  I tested this using the [Human Powered Quicksort](https://github.com/sfu-db/reprowd/blob/master/reprowd/examples/quicksort.py ) example.   [Here](http://ec2-54-200-84-187.us-west-2.compute.amazonaws.com:5000/project/imgcmp-testing-s24/newtask) is the link to the project where you can test the issue.

**Comment by jnwang** [comment]
Would you like to send a pull request to fix the issue?

**Comment by VHUCXAONG** [comment]
OK got it.


----- Original Message -----

**Comment by jnwang** [comment]
What I meant is that if @saifcharaniya would like to do it, he can send a pull request to get some bonus points. Otherwise, @VHUCXAONG can fix the issue.

**Comment by VHUCXAONG** [comment]
OK got it.

**Comment by saifcharaniya** [comment]
I tested again with Safari v10.0 and the issue is no longer present.
